### ISSUE TITLE
No auto redirect to Keycloak after opening Jitsi

### ISSUE THREAD

**Issue by s0rd3s** [nordeck/jitsi-keycloak-adapter-v2#2]
Good afternoon. After installing and configuring the adapter on VM Jitsi does not redirect me to keycloak.
When I'm testing token auth using Jitok, it works fine. That is, clicking on a link with a jwt token creates a room with the right parameters and authorizes under the right user.
When I've tried to visit https://domain.com/oidc/ it gives me 404.
Because I'm using official ansible role for deploing Jitsi istelf, I've had to add oicd config to nginx config, but not creating another one like you are asking in step 4 of the guide.

**Steps To Reproduce**

1. Open jitsi.domain.com
2. See error(no keycloak redirect)

**Expected behavior**
I need login to Jitsi room using KeyCloak

**Environment:**
 - OS: Ubuntu 22.04.5 LTS, Standalone ada
 - Browser: [firefox, safari]
 - Version Keycloak: [20.0.3]

**Additional context**

The installation was done using Ansible playbook, which is based on the instructions from the [repository](https://github.com/nordeck/jitsi-keycloak-adapter-v2/blob/main/docs/setup-standalone.md).

```
- name: Install jitsi-meet-tokens
      apt:
        name: jitsi-meet-tokens
        state: present

    - name: Update authentication method in Prosody config (first occurrence only)
      lineinfile:
        path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
        regexp: '^\s*authentication\s*=.*$'
        line: '    authentication = "token"'
        firstmatch: true

    - name: Update app_id in Prosody config
      replace:
        path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
        regexp: '^.*app_id\s*=.*$'
        replace: '    app_id="{{ jitsi_meet_app_id }}"'

    - name: Update app_secret in Prosody config
      replace:
        path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
        regexp: '^.*app_secret\s*=.*$'
        replace: '    app_secret="{{ jitsi_meet_app_secret }}"'

    - name: Restart Prosody
      ansible.builtin.systemd_service:
        state: restarted
        name: prosody

    - name: Install Deno
      unarchive:
        src: https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip
        dest: /usr/local/bin/
        remote_src: true
        mode: '755'
        creates: /usr/local/bin/deno

    - name: Create adapter user
      user:
        name: adapter
        system: true
        create_home: true

    - name: Ensure /home/adapter/app/ directory exists
      ansible.builtin.file:
        path: /home/adapter/app/
        state: directory
        owner: adapter
        group: adapter
        mode: '755'

    - name: Populate adapter app using templates
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/home/adapter/app/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: '644'
        owner: adapter
        group: adapter
      with_fileglob:
        - "files/app/*.j2"

    - name: Create systemd oidc unit
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item | basename | regex_replace('\\.j2$', '') }}"
        mode: '644'
      with_fileglob:
        - "files/unit/*.j2"

    - name: Restart oidc-adapter
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        state: restarted
        name: oidc-adapter

    - name: Configure Nginx for Keycloak OIDC
      blockinfile:
        path: "/etc/nginx/sites-available/{{ jitsi_meet_server_name }}.conf"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Keycloak OIDC"
        block: |
          location ~ /oidc/ {
              proxy_pass http://127.0.0.1:9000;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-For $remote_addr;
              proxy_set_header Host $http_host;
          }
        insertafter: "gzip_min_length 512;"

    - name: Restart Nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx

    - name: Add tokenAuthUrl to Jitsi config.js
      lineinfile:
        path: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
        line: "config.tokenAuthUrl = 'https://{{ jitsi_meet_server_name }}/oidc/auth?state={state}';"
        insertafter: EOF

    - name: Enable tokenAuthUrlAutoRedirect in Jitsi config.js
      lineinfile:
        path: "/etc/jitsi/meet/{{ jitsi_meet_server_name }}-config.js"
        line: "config.tokenAuthUrlAutoRedirect = true;"
        insertafter: EOF

    - name: Enable persistent_lobby in Prosody
      replace:
        path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
        regexp: '^(.*modules_enabled\s*=\s*\{.*)"ping"; -- Enable mod_ping(.*)$'
        replace: |
          \1"ping"; -- Enable mod_ping
              "persistent_lobby";\2

    - name: Restart Prosody
      ansible.builtin.systemd_service:
        state: restarted
        name: prosody

    - name: Enable muc_wait_for_host in Prosody # That block don't work properly, but not a problem, changing that config by hands for now
      blockinfile:
        path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
        marker: "-- {mark} ANSIBLE MANAGED BLOCK"
        block: |
          modules_enabled = {
              "muc_meeting_id";
              "muc_domain_mapper";
              "polls";
              --"token_verification";
              "muc_rate_limit";
              "muc_wait_for_host";
          }
        insertafter: '^Component "conference\.{{ jitsi_meet_server_name }}" "muc"'

    - name: Restart Prosody
      ansible.builtin.systemd_service:
        state: restarted
        name: prosody

    - name: Enable allow_empty_token in Prosody
      lineinfile:
        path: "/etc/prosody/conf.d/{{ jitsi_meet_server_name }}.cfg.lua"
        line: "    allow_empty_token=true"
        insertafter: 'app_secret='

    - name: Restart Prosody
      ansible.builtin.systemd_service:
        state: restarted
        name: prosody

    - name: Create guest domain config for Prosody
      copy:
        dest: "/etc/prosody/conf.avail/guest.cfg.lua"
        content: |
          VirtualHost "guest.domain.loc"
              authentication = "jitsi-anonymous"
              c2s_require_encryption = false
        mode: '644'

    - name: Create symlink for guest domain in Prosody
      file:
        src: "../conf.avail/guest.cfg.lua"
        dest: "/etc/prosody/conf.d/guest.cfg.lua"
        state: link

    - name: Restart Prosody
      ansible.builtin.systemd_service:
        state: restarted
        name: prosody

    - name: Find all matching Jitsi config.js files on the remote server
      find:
        paths: /etc/jitsi/meet/
        patterns: "*-config.js"
        recurse: no
      register: config_files

    - name: Set anonymousdomain in all matching Jitsi config.js files
      lineinfile:
        path: "{{ item.path }}"
        line: "config.hosts.anonymousdomain = 'guest.domain.loc';"
        insertafter: EOF
      loop: "{{ config_files.files }}"
      when: config_files.matched > 0
```
